version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker-compose build -t ethmonitor .
      - run:
          name: Unit Tests 
          command: docker-compose run producer go test
      - run: 
          name: Push Docker image to repo
          command: |
            docker tag ethmonitor:latest ${DOCKER_REPO}/ethmonitor:latest 
            docker push ${DOCKER_REPO}/ethmonitor:latest
            docker tag ethmonitor:latest ${DOCKER_REPO}/ethmonitor:${CIRCLE_SHA1}
            docker push ${DOCKER_REPO}/ethmonitor:${CIRCLE_SHA1}

