version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker-compose build
      - run:
          name: Unit Tests 
          command: docker-compose run producer go test
      - run: | 
         TAG=0.1$CIRCLE_BUILD_NUM
	 docker-compose build 	   
	 docker login -u $DOCKER_USER -p $DOCKER_PASS
	 docker-compose push brandonbryant/ethmonitor:$TAG
