version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker-compose build 
      - run:
          name: Unit Tests 
          command: docker-compose run producer go test
      - run: 
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Push Docker image to repo
          command: |
            docker tag project_producer:latest ${DOCKER_REPO}/project_producer:latest 
            docker push ${DOCKER_REPO}/project_producer:latest
            docker tag project_producer:latest ${DOCKER_REPO}/project_producer:${CIRCLE_SHA1}
            docker push ${DOCKER_REPO}/project_producer:${CIRCLE_SHA1}
      - run:
          name: Deploy image to server 
          command: ssh chef@199.188.207.179 sudo chef-client -o recipe[anypay_eth::oracle]
