version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker-compose build -p ethmonitor 
      - run:
          name: Unit Tests 
          command: docker-compose run producer go test
      - run: 
          name: Docker login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Push Docker image to repo
          command: |
            docker tag ethmonitor_producer:latest ${DOCKER_REPO}/ethmonitor_producer:latest 
            docker push ${DOCKER_REPO}/project_producer:latest
            docker tag eth_monitor_producer:latest ${DOCKER_REPO}/ethmonitor_producer:${CIRCLE_SHA1}
            docker push ${DOCKER_REPO}/ethmonitor_producer:${CIRCLE_SHA1}

