version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker-compose build
      - run:
          name: Unit Tests 
          command: go test
     # - run:
     #     command: docker-compose up
