version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Docker build
          command: docker-compose build -t=brandonbryant/EthMonitor:v1 .
      - run:
          name: Unit Tests 
          command: docker-compose run producer go test
      - run:
	  name: Login to Docker Hub
          command: docker login login $DOCKER_USER -p $DOCKER_PASS 
      - run:
	  name: Push image
	  command: docker push brandonbryant/ethmonitor:v1 
